apiVersion: batch/v1
kind: Job
metadata:
  name: ingestion-job
  namespace: ingestion
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: ingestion
        image: otaciliopsf/cde-bootcamp:desafio-mod4-ingestion
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        env:
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: azure-service-account
                key: AZURE_CLIENT_ID
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: azure-service-account
                key: AZURE_CLIENT_SECRET
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: azure-service-account
                key: AZURE_TENANT_ID
          - name: STG_ACC_NAME
            valueFrom:
              configMapKeyRef:
                name: lake-config
                key: storage_account_name
          - name: LAKE_NAME
            valueFrom:
              configMapKeyRef:
                name: lake-config
                key: file_system_name
          - name: PYTHONUNBUFFERED
            value: "1"
      restartPolicy: Never