apiVersion: v1
kind: Pod
metadata:
  name: ingestion-pod-
  namespace: ingestion
spec:
  containers:
  - name: ingetion
    image: otaciliopsf/cde-bootcamp:desafio-mod4-ingestion
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "1"
        memory: "800Mi"
    env:
      - name: AZURE_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: azure-service-account
            key: AZURE_CLIENT_ID
      - name: AZURE_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: azure-service-account
            key: AZURE_CLIENT_SECRET
      - name: AZURE_TENANT_ID
        valueFrom:
          secretKeyRef:
            name: azure-service-account
            key: AZURE_TENANT_ID
  restartPolicy: Never